import { type Client } from "@libsql/client";

import { db } from "@/lib/db";
import type { ResponseTimerStatus } from "@/lib/db/services/response-timer-status";
import { createResponseTimer } from "@/lib/db/services/response-timer.service";
import { updateHeartbeat } from "@/lib/db/services/session.service";
import { notifySocketServer } from "@/lib/socket-emitter";

export type UserAuctionState = "miglior_offerta" | "rilancio_possibile" | "asta_abbandonata";
interface UserAuctionStates { [userId: string]: UserAuctionState; }
export interface AuctionStateRow { auction_id: number; player_id: number; player_name: string; player_team: string; player_photo_url: string | null; current_highest_bidder_id: string; current_highest_bid_amount: number; response_deadline: number | null; activated_at: number | null; cooldown_ends_at: number | null; }
export interface UserAuctionStateDetail { auction_id: number; player_id: number; player_name: string; player_team: string; player_photo_url: string | null; current_bid: number; user_state: UserAuctionState; response_deadline: number | null; time_remaining: number | null; is_highest_bidder: boolean; }

export const getUserAuctionStates = async (userId: string, leagueId: number): Promise<UserAuctionStateDetail[]> => {
  await updateHeartbeat(userId);
  const now = Math.floor(Date.now() / 1000);
  const result = await db.execute({ sql: `SELECT a.id as auction_id, a.player_id, p.name as player_name, p.team as player_team, p.photo_url as player_photo_url, a.current_highest_bidder_id, a.current_highest_bid_amount, urt.response_deadline, urt.activated_at, upp.expires_at as cooldown_ends_at FROM auctions a JOIN players p ON a.player_id = p.id JOIN bids b ON a.id = b.auction_id AND b.user_id = ? LEFT JOIN user_auction_response_timers urt ON a.id = urt.auction_id AND urt.user_id = ? AND urt.status = 'pending' LEFT JOIN user_player_preferences upp ON a.player_id = upp.player_id AND upp.user_id = ? AND upp.league_id = a.auction_league_id AND upp.preference_type = 'cooldown' AND upp.expires_at > ? WHERE a.auction_league_id = ? AND a.status = 'active' GROUP BY a.id`, args: [userId, userId, userId, now, leagueId] });
  return (result.rows as unknown as AuctionStateRow[]).map((auction) => { const isHighestBidder = auction.current_highest_bidder_id === userId; const isInCooldown = Boolean(auction.cooldown_ends_at && auction.cooldown_ends_at > now); return { auction_id: auction.auction_id, player_id: auction.player_id, player_name: auction.player_name, player_team: auction.player_team, player_photo_url: auction.player_photo_url, current_bid: auction.current_highest_bid_amount, user_state: isInCooldown ? "asta_abbandonata" : isHighestBidder ? "miglior_offerta" : "rilancio_possibile", response_deadline: auction.response_deadline, time_remaining: auction.response_deadline ? Math.max(0, auction.response_deadline - now) : null, is_highest_bidder: isHighestBidder }; });
};

export const getUserAuctionState = async (auctionId: number, userId: string): Promise<UserAuctionState> => { try { const result = await db.execute({ sql: "SELECT user_auction_states, current_highest_bidder_id FROM auctions WHERE id = ?", args: [auctionId] }); const auction = result.rows[0]; if (!auction) return "miglior_offerta"; if (auction.current_highest_bidder_id === userId) return "miglior_offerta"; const states: UserAuctionStates = auction.user_auction_states ? JSON.parse(auction.user_auction_states as string) : {}; return states[userId] || "miglior_offerta"; } catch (error) { console.error(`[AUCTION_STATES] Error getting state for user ${userId}, auction ${auctionId}:`, error); return "miglior_offerta"; } };

export const setUserAuctionStateInTx = async (executor: Pick<Client, "execute">, auctionId: number, userId: string, state: UserAuctionState): Promise<void> => { const result = await executor.execute({ sql: "SELECT user_auction_states, current_highest_bidder_id, player_id FROM auctions WHERE id = ?", args: [auctionId] }); const auction = result.rows[0]; if (!auction) throw new Error(`Auction ${auctionId} not found`); const currentStates: UserAuctionStates = auction.user_auction_states ? JSON.parse(auction.user_auction_states as string) : {}; currentStates[userId] = state; await executor.execute({ sql: "UPDATE auctions SET user_auction_states = ? WHERE id = ?", args: [JSON.stringify(currentStates), auctionId] }); };

export const setUserAuctionState = async (auctionId: number, userId: string, state: UserAuctionState): Promise<void> => { await setUserAuctionStateInTx(db, auctionId, userId, state); const auctionResult = await db.execute({ sql: "SELECT current_highest_bidder_id, player_id FROM auctions WHERE id = ?", args: [auctionId] }); const auction = auctionResult.rows[0] as unknown as { current_highest_bidder_id: string; player_id: number } | undefined; await notifySocketServer({ room: `user-${userId}`, event: "auction-state-changed", data: { auctionId, playerId: auction?.player_id, newState: state, isHighestBidder: auction?.current_highest_bidder_id === userId } }); };

export const handleBidderChange = async (auctionId: number, previousBidderId: string | null, newBidderId: string): Promise<void> => { if (previousBidderId && previousBidderId !== newBidderId) { await setUserAuctionState(auctionId, previousBidderId, "rilancio_possibile"); await createResponseTimer(auctionId, previousBidderId); } };

export const handleAuctionAbandon = async (auctionId: number, userId: string): Promise<void> => { const now = Math.floor(Date.now() / 1000); await setUserAuctionState(auctionId, userId, "asta_abbandonata"); const auctionResult = await db.execute({ sql: "SELECT auction_league_id, player_id FROM auctions WHERE id = ?", args: [auctionId] }); const auction = auctionResult.rows[0]; await db.execute({ sql: "UPDATE user_auction_response_timers SET status = ?, processed_at = ? WHERE auction_id = ? AND user_id = ? AND status = 'pending'", args: ["abandoned" satisfies ResponseTimerStatus, now, auctionId, userId] }); if (auction) { const cooldownEnd = now + 48 * 3600; await db.execute({ sql: "INSERT INTO user_player_preferences (user_id, player_id, league_id, preference_type, expires_at, created_at, updated_at) VALUES (?, ?, ?, 'cooldown', ?, ?, ?) ON CONFLICT(user_id, player_id, league_id) DO UPDATE SET preference_type = 'cooldown', expires_at = excluded.expires_at, updated_at = excluded.updated_at", args: [userId, auction.player_id, auction.auction_league_id, cooldownEnd, now, now] }); } };

export const getUsersWithPendingResponse = async (leagueId: number): Promise<Array<{ user_id: string; auction_id: number; player_id: number; player_name: string; response_deadline: number }>> => { const result = await db.execute({ sql: "SELECT DISTINCT urt.user_id, urt.auction_id, a.player_id, p.name as player_name, urt.response_deadline FROM user_auction_response_timers urt JOIN auctions a ON urt.auction_id = a.id JOIN players p ON a.player_id = p.id WHERE a.auction_league_id = ? AND urt.status = 'pending' AND a.status = 'active' ORDER BY urt.response_deadline ASC", args: [leagueId] }); return result.rows.map((row) => ({ user_id: row.user_id as string, auction_id: row.auction_id as number, player_id: row.player_id as number, player_name: row.player_name as string, response_deadline: row.response_deadline as number })); };

export const processExpiredResponseStates = async (): Promise<{ processedCount: number; errors: string[] }> => { const now = Math.floor(Date.now() / 1000); const result = await db.execute({ sql: "SELECT urt.auction_id, urt.user_id FROM user_auction_response_timers urt JOIN auctions a ON urt.auction_id = a.id WHERE urt.status = 'pending' AND urt.response_deadline <= ? AND a.status = 'active'", args: [now] }); const errors: string[] = []; let processedCount = 0; for (const timer of result.rows) { try { await handleAuctionAbandon(timer.auction_id as number, timer.user_id as string); processedCount++; } catch (error) { errors.push(`User ${timer.user_id}, Auction ${timer.auction_id}: ${error instanceof Error ? error.message : "Unknown error"}`); } } return { processedCount, errors }; };
