-- Historical migration retained for traceability.
-- The current schema already defines UNIQUE(auction_id, user_id), with the
-- supported statuses: pending, cancelled, abandoned, expired.
-- Do not run the old table-rebuild procedure: it referenced the removed
-- notified_at column and incompatible status values.
-- Existing databases must use the current schema/migration path instead.
